### ISSUE TITLE
nix-shell-action doesn't work with nix 2.4

### ISSUE THREAD

**Issue by Raffo** [workflow/nix-shell-action#193]
This project is using `nix -c` in https://github.com/workflow/nix-shell-action/blob/main/src/main.ts#L23 which is not present anymore in the `nix` command from nix 2.4 due to a significant refactor of the command itself, see release notes in https://nixos.org/manual/nix/unstable/release-notes/rl-2.4.html . 

The error looks like the following: 

```
error: unrecognised flag '-c'
12
Try 'nix --help' for more information.
13
Error: Error Error: Command failed: bash -c /home/runner/work/_actions/workflow/nix-shell-action/v1/dist/wrapper.sh, action may still succeed though
14
Error: Command failed: bash -c /home/runner/work/_actions/workflow/nix-shell-action/v1/dist/wrapper.sh
```

I believe a possible workaround is to stick to nix 2.1.

**Comment by workflow** [comment]
Good point! We can detect new nix versions and change the invocation accordingly.
