### ISSUE TITLE
shell.nix not used?

### ISSUE THREAD

**Issue by jamesward** [workflow/nix-shell-action#291]
Caveat: I'm a noob to a lot of this.  I expected this action to load my `shell.nix` but that doesn't seem to be the case.  Can you clarify?  Thanks!

**Comment by rrbutani** [comment]
Currently, this action is [built on `nix shell`](https://github.com/workflow/nix-shell-action/blob/0a573af0eac8ee96a41b2b029576afca28a1031c/src/main.ts#L45-L52) (note: not `nix-shell`) and requires that you specify the packages you want to use from `nixpkgs` [as an argument to the action](https://github.com/workflow/nix-shell-action/blob/0a573af0eac8ee96a41b2b029576afca28a1031c/.github/workflows/test.yml#L40).

If you're only relying on your `shell.nix` to add things to `$PATH` (i.e. no `shellHook`, no stdenv hooks, no other env vars) then you should be pass your package list directly to this action.

Alternatively, [`use-nix-shell-action`](https://github.com/rrbutani/use-nix-shell-action) will accept a `shell.nix`.
