### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by TanvirOnGH** [workflow/nix-shell-action#310]
Getting these errors:

![image](https://github.com/workflow/nix-shell-action/assets/138336161/36713951-6a22-4ff8-afa8-b4abbd2072bd)

The repository doesn't seem to be actively maintained anymore. I use it on my repo (also found many others using it), any chance to update the action to use Node.js 20+? And merge the important [PRs](https://github.com/workflow/nix-shell-action/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies)?

@workflow

**Comment by workflow** [comment]
Yep thanks for pinging me @TanvirOnGH, happy to do that in the next days.

**Comment by workflow** [comment]
Upgraded and released as [v3.3.1](https://github.com/workflow/nix-shell-action/releases/tag/v3.3.1), any remaining problems let me @TanvirOnGH !
